# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aXUE8w4Nsq7YejUbySKP+mFDrtgihDN9frhEXp6Zps2Evc1v52Txv0qt/6T48pZNv7TsBFIwMpTm7e7HeQHFsH7/sc47ruW3anZ63z6T/j9HIcy1vFnW0zDEnrfEnvs5vaMvedVysKmzOe624isbJ8dQn5ZZdEzyTrZBUg21flTkTp59vh9h+VPlYmwi4DOOxOFHZWOmbGOGnpKOqO/GM9bz1pgvX79lGlqZtGdTYvPjhbkP/X6aOwk95g1oZ0Qp9+iCqucnsoHhN3wrgniI78EWYMXIO+23hLkbcpCKzl8Vmbd8h4Ze80qUwuuMMk/SV30vzdt7Jiep0Qjx3KLomKFceFeLGZ0AuDz54Yrf/ZaC3+ZB+QSZu0L09RTrR1IpmD+xOI/8WFXTsPp9OO03em5PRYqQAFLwBaVbxOgYNdNQUnyqJ+nfDghlmsMdVv2aGo7jFFSVZCWuI7cd7pZ7IUHAqf08zaMgBzIrny/RO5wEtQUlF56GnWTtD+vMV+653o2PXa8xY9rBo8r3+u+hWRDtXIX5Ra3ZbrJuYAYGnM7YrN+RsnoDVPeuoyqO+jXoUwWlray7gGkFrRZxR+Hrusipx/8ciRg8YRqZsvWRPMRbAsl6Rlqr1m7R+8kZa1ASBSv286UB/QwIR0kYbQkrK62jYNcbcua1LOOW+MifZtA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
