travis:
  secure:
    BINSTAR_TOKEN: aXUE8w4Nsq7YejUbySKP+mFDrtgihDN9frhEXp6Zps2Evc1v52Txv0qt/6T48pZNv7TsBFIwMpTm7e7HeQHFsH7/sc47ruW3anZ63z6T/j9HIcy1vFnW0zDEnrfEnvs5vaMvedVysKmzOe624isbJ8dQn5ZZdEzyTrZBUg21flTkTp59vh9h+VPlYmwi4DOOxOFHZWOmbGOGnpKOqO/GM9bz1pgvX79lGlqZtGdTYvPjhbkP/X6aOwk95g1oZ0Qp9+iCqucnsoHhN3wrgniI78EWYMXIO+23hLkbcpCKzl8Vmbd8h4Ze80qUwuuMMk/SV30vzdt7Jiep0Qjx3KLomKFceFeLGZ0AuDz54Yrf/ZaC3+ZB+QSZu0L09RTrR1IpmD+xOI/8WFXTsPp9OO03em5PRYqQAFLwBaVbxOgYNdNQUnyqJ+nfDghlmsMdVv2aGo7jFFSVZCWuI7cd7pZ7IUHAqf08zaMgBzIrny/RO5wEtQUlF56GnWTtD+vMV+653o2PXa8xY9rBo8r3+u+hWRDtXIX5Ra3ZbrJuYAYGnM7YrN+RsnoDVPeuoyqO+jXoUwWlray7gGkFrRZxR+Hrusipx/8ciRg8YRqZsvWRPMRbAsl6Rlqr1m7R+8kZa1ASBSv286UB/QwIR0kYbQkrK62jYNcbcua1LOOW+MifZtA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
